name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        name: language plugin
        with:
          filename: language.svg
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_languages: yes
          plugin_languages_ignored: html, css
      - uses: lowlighter/metrics@latest
        name: achievement plugin
        with:
          filename: achievement.svg
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_achievements: yes
      - name: Recent Activity Charts
        uses: lowlighter/metrics@latest
        with:
          base: ""
          filename: habits.svg
          plugin_habits: yes
          plugin_habits_facts: no
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_habits_charts: yes
          config_timezone: America/Los_Angeles
      - name: Half-year calendar
        uses: lowlighter/metrics@latest
        with:
          filename: iso-calendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes